### ISSUE TITLE
Include Dependabot and an automated Workflow to publish to Maven in the Project

### ISSUE THREAD

**Issue by NewCeptionDev** [HotelsDotCom/avro-compatibility#9]
Hi.

We would like to use this project in our workflow at Hapag Llyod.
As we are required to make sure that all dependencies are up to date to reduce security risks, we sadly can't use the project in it's current state.

I've seen that you are using dependabot to automatically update dependencies in some of your other open source projects.
You also seem to have some projects with Github Workflows allowing changes to be automatically published to maven.

Would you be able to include those tools in this repository as well, so that the dependencies will easily be kept up to date without much effort for you?

We would really appreciate it.
Thanks a lot
Julius

PS: If you want, we can also try to make the changes and create a PR for them, so that you will only need to add the required variables to the project.

**Comment by NewCeptionDev** [comment]
Following a deeper investigation on what parts from this project we would need to use, we found out, that it will be easier for us to directly use the apache avro dependency and add some custom error translation.
Sorry for any trouble caused.

**Comment by massdosage** [comment]
No problem @NewCeptionDev, if you can find what you need in Avro itself that would be a better solution. If for some reason you find you do need to use this repo we'd be happy to review a PR that upgrades the dependencies.
